### ISSUE TITLE
404 error when running snapshot in domino 4.6.4

### ISSUE THREAD

**Issue by ddl-ymaachi** [dominodatalab/domino-maintenance-mode#3]
this happened when running dmm against a domino 4.6.4 installation.  I’m unsure if the 404 errors indicate that some required data could not be found (due to API changes), or if the error is unimportant. 

Command: 
```bash
docker run -v `pwd`/export:/export -v /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-certificates.crt:ro -e DOMINO_API_KEY=XXXX  -e DOMINO_HOSTNAME=https://nexus-domino.inv.adroot.lgim.com/ -e DOMINO_SSL_NO_VERIFY=false -e REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt --rm -a stdout -it [quay.io/domino/dmm](http://quay.io/domino/dmm) snapshot /export/prod.json | tee output.txt | grep -E -e '(:domino_maintenance_mode|^[^ ]\+:\s)' | tee trimmed.txt
```

attached the [output.txt](https://github.com/dominodatalab/domino-maintenance-mode/files/10140539/output.txt) (complete output) and [trimmed.txt](https://github.com/dominodatalab/domino-maintenance-mode/files/10140541/trimmed.txt) (result of the grep)

**Comment by ddl-m-coaker** [comment]
Moved to Jira ([DOM-43623](https://dominodatalab.atlassian.net/browse/DOM-43623))
