### ISSUE TITLE
Vendor image with Domino so that its easier to use offline

### ISSUE THREAD

**Issue by ddl-kevin** [dominodatalab/domino-maintenance-mode#4]
If this image were bundled with Domino images, then users would already have it in their registry when they need to run it for a their version. 

We may need to switch to using an OSRP base image so that it can pass security scans.

**Comment by ddl-m-coaker** [comment]
Moved to Jira ([DOM-43624](https://dominodatalab.atlassian.net/browse/DOM-43624))
